In [328]:
import numpy as np
import pandas as pd

# データの読み込み
node = pd.read_csv('node.csv')
spring = pd.read_csv('spring.csv')

print(node)
print(spring)

# 各節点にかかる力
force = np.array(node.ix[:,3])

# 各ばねのばね定数
k = spring.ix[:, 3]

# 剛性マトリクス
stmx = np.zeros((len(node.ix[:, 0]),len(node.ix[:, 0])))
size = node.ix[:,0].size
i = 0

for i in list(range(size)):
    if i == 0:
        stmx[0, 0] = k[0]
        stmx[0, 1] = k[0] * (-1)

    elif i == size - 1:
        stmx[i, i-1] = k[i-1] * (-1)
        stmx[i, i] = k[i-1]

    else:
        stmx[i, i-1] = k[i-1] * (-1)
        stmx[i, i] = k[i-1] + k[i]
        stmx[i, i+1] = k[i] * (-1)

# 支持条件を読み込んで、固定→計算から削除
# Kaaの抽出しかしてない→固定の支持条件しか計算できない
i = 0
fix = 1
for i in list(range(node.ix[:,2].size)):
    if node.ix[i,2] == 'fix':
        stmx = np.delete(stmx, i, 0)
        stmx = np.delete(stmx, i, 1)
        force = np.delete(force, i, 0)
        print('u', i + 1, '= 0.0')
        fix = fix + 1
    else:
        pass
    i = i + 1

# 連立方程式を解く
x = np.linalg.solve(stmx, force)

i = 0
for i in list(range(force.size)):
    print('u', i + fix,'=', x[i])


   Point No  CorrdiX support  force
0         1        0     fix      0
1         2        1    free      5
2         3        2    free      5
   Spring No  Point1  Point2  constant
0          1       1       2         1
1          2       2       3         1
u 1 = 0.0
u 2 = 10.0
u 3 = 15.0


In [206]:
import numpy as np
import pandas as pd

# データの読み込み
node = pd.read_csv('node.csv')
spring = pd.read_csv('spring.csv')

# 各節点にかかる力
force = node.ix[:,3]

# 各ばねのばね定数
k = spring.ix[:, 3]

# 剛性マトリクス
stmx = np.array([[k[0], -k[0], 0],
                 [-k[0], k[0]+k[1], -k[1]],
                 [0, -k[1], k[1]]])


a, b = np.split(stmx, [2], axis=0)
aa, ab = np.split(a, [2], axis=1)
ba, bb = np.split(b, [2], axis=1)
print(stmx)
print(aa, ab, ba, bb)

[[ 1 -1  0]
 [-1  2 -1]
 [ 0 -1  1]]
[[ 1 -1]
 [-1  2]] [[ 0]
 [-1]] [[ 0 -1]] [[1]]


In [322]:
import numpy as np
import pandas as pd

# データの読み込み
node = pd.read_csv('node.csv')
spring = pd.read_csv('spring.csv')

print(node)
print(spring)

# 各節点にかかる力
force = np.array(node.ix[:,3])

# 各ばねのばね定数
k = spring.ix[:, 3]

# 剛性マトリクス
stmx = np.zeros((len(node.ix[:, 0]),len(node.ix[:, 0])))
size = node.ix[:,0].size
i = 0

for i in list(range(size)):
    if i == 0:
        stmx[0, 0] = k[0]
        stmx[0, 1] = k[0] * (-1)

    elif i == size - 1:
        stmx[i, i-1] = k[i-1] * (-1)
        stmx[i, i] = k[i-1]

    else:
        stmx[i, i-1] = k[i-1] * (-1)
        stmx[i, i] = k[i-1] + k[i]
        stmx[i, i+1] = k[i] * (-1)

stmx

   Point No  CorrdiX support  force
0         1        0     fix      0
1         2        1    free      0
2         3        2    free      5
3         4        3    free      3
   Spring No  Point1  Point2  constant
0          1       1       2         1
1          2       2       3         1
2          3       3       4         2


array([[ 1., -1.,  0.,  0.],
       [-1.,  2., -1.,  0.],
       [ 0., -1.,  3., -2.],
       [ 0.,  0., -2.,  2.]])

In [1]:
import numpy as np

A = np.array([[6, 4, 1],
              [1, 8, -2],
              [3, 2, 0]])
b = np.array([7, 6, 8])

x = np.linalg.solve(A, b)

print(x)

[ 4. -2. -9.]


In [142]:
list(range(node.ix[:,2].size))

[0, 1, 2]

In [27]:
comprehension_1= [i for i in range(10)]
comprehension_1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]